### ISSUE TITLE
Phiremock is started on every suite

### ISSUE THREAD

**Issue by michaelarnauts** [mcustiel/phiremock-codeception-extension#23]
Is it correct behavior that phiremock is started on every suite? I don't need it for my unit tests, but I do need it for my functional tests.

I have not added it to the `unit.suite.yml` file, but it is started anyway. It seems it is started trough the extension, but can't it be started only when the module also has phiremock configured?

**Comment by niksamokhvalov** [comment]
Check whether the completed work Phiremock after passing the tests. See `ps -ax`.

**Comment by michaelarnauts** [comment]
If I only run the unit tests, it is also started, and that's not needed.

**Comment by mcustiel** [comment]
Hello @michaelarnauts 
If you have codeception >= 2.2.7 you can specify the extensions config per suite. So by adding the extension section to your functional tests, you will solve this problem.
Please confirm if this works to you and if it does, I will close this issue.

**Comment by michaelarnauts** [comment]
That's working nicely. It might be nice to have this documented in the docs?

**Comment by mcustiel** [comment]
Sure. Will do it. Do you agree with closing this issue?

**Comment by mcustiel** [comment]
Added note to the documentation.

**Comment by amkoro** [comment]
I'm using phiremock-codeception-extension in Yii2 advanced template. My Phiremock extension configuration located in the root codeception.yml.

Running all tests causing Phiremock daemon to start in each suite. But the main issue, that it is trying to start without stopping the previous instance. And it is causing error that "can't start Phiremock on xxx port" due to previous Phiremock instance already listening that port.

And moreover, the tests are not complete properly - the Phiremock daemon didn't shutdown (it need's to be killed by "killall php" command).

I think this behavior is not correct. If I added Phiremock extension to my root codeception.yml it should run one Phiremock instance during start and correctly shutdown it after all tests from all suites completed.

This issue exists in 1.5.1. I reverted to 1.5.0 as it works correct for me.
